Github Action
avisi-cloud/structurizr-site-generatr pull request #304
Opened 2023-09-04 14:45 UTC by bahulneel

Added the ability to run as a GitHub action and updated README

2023-09-08 07:25 UTC, dirkgroot requested changes
Hi @bahulneel, thanks for your PR! Apart from a couple of spelling errors, it looks good to me.

2023-09-08 07:25 UTC, dirkgroot commented on README.md
> +Here's a complete example of publishing main, deveop and PR docs to github pages (the token also will need readfor PRs and write for pages):
```suggestion
Here's a complete example of publishing main, deveop and PR docs to github pages (the token also will need read for PRs and write for pages):
```

2023-09-08 07:25 UTC, dirkgroot commented on README.md
> +The action will use the github workspace, rather that `/var/model`.
```suggestion
The action will use the github workspace, rather than `/var/model`.
```

2023-09-08 07:25 UTC, dirkgroot commented on action.yml
> +    description: Comma-separated list of branches to injclude in the generated site
```suggestion
    description: Comma-separated list of branches to include in the generated site
```

2023-10-10 12:44 UTC, jp7677 commented
Not sure if we should include and maintain a GitHub action in this repository. An alternative would be an entry here describing the setup of the action and its usage https://github.com/avisi-cloud/structurizr-site-generatr/discussions/categories/q-a 
I'll leave that one to @dirkgroot

2023-10-10 14:24 UTC, bahulneel commented
The uses: directive in the workflow expects a GitHub repository. This is the reason I put it here, I'm not aware of an alternative method that is as convenient.

Crafting external actions can be a non-trivial exercise, I hope colocating with the source will save others the difficulty.

2023-10-11 18:18 UTC, jp7677 commented
> The uses: directive in the workflow expects a GitHub repository. This is the reason I put it here, I'm not aware of an alternative method that is as convenient.
> 
> Crafting external actions can be a non-trivial exercise, I hope colocating with the source will save others the difficulty.

OK, fair point. What about only adding the github action itself to the repo and move the usage guide to the `q-a` section in discussions.

2023-10-19 16:42 UTC, bahulneel commented
I sometimes worry about moving useful usage information outside the codebase, I could move the instructions to a separate markdown file and then we could reference it in the q-a.

2023-11-24 07:48 UTC, dirkgroot requested changes

2023-11-24 07:48 UTC, dirkgroot commented on README.md
> +Here's a complete example of publishing main, deveop and PR docs to github pages (the token also will need read for PRs and write for pages):
```suggestion
Here's a complete example of publishing main, develop and PR docs to github pages (the token also will need read for PRs and write for pages):
```

2023-11-24 07:48 UTC, dirkgroot commented on README.md
> +Additionally, you will need to generate a personal acess token with, at least, read access to your repository.
You don't always need a personal access token. This repository is public, so if you provide Structurizr Site Generatr with a `https://` URL, a PAT isn't needed. See for example https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/.github/workflows/release.yml#L165.

2024-01-08 15:03 UTC, dirkgroot commented
Due to inactivity I'm closing this pull request now. Feel free to reopen it if you want to continue development.

2024-01-08 15:03 UTC, closed without merging