Branch list tidy up
avisi-cloud/structurizr-site-generatr pull request #322
Opened 2023-10-13 15:14 UTC by qtzar

Sorts the list of branches in a multi-branch site and moves the default branch to the top of the list.

2023-10-13 19:16 UTC, jp7677 requested changes
See comments.

2023-10-13 19:16 UTC, jp7677 commented on src/main/kotlin/nl/avisi/structurizr/site/generatr/GenerateSiteCommand.kt
> +        val branchNames: List<String> = if (allBranches)
This change is not needed.

2023-10-13 19:16 UTC, jp7677 commented on src/main/kotlin/nl/avisi/structurizr/site/generatr/GenerateSiteCommand.kt
> +        val sortedBranchNames = branchesToGenerate.toMutableList()
We can do this more elegantly. My proposal:

Introduce a custom comparator for our needs on the top level of this file:

```kotlin
fun branchComparator(defaultBranch: String) = Comparator<String> { a, b ->
    if (a == defaultBranch) -1
    else if (b == defaultBranch) 1
    else a.compareTo(b)
}
```

The test for that one would look like:

```kotlin
class BranchComparatorTest {
    @TestFactory
    fun `default branch first then by string`() = listOf(
        listOf("a", "b", "main"),
        listOf("a", "main", "b"),
        listOf("b", "a", "main"),
        listOf("b", "main", "a"),
        listOf("main", "a", "b"),
        listOf("main", "b", "a")
    ).map { branches ->
        DynamicTest.dynamicTest(branches.toString()) {
            assertThat(branches.sortedWith(branchComparator("main")))
                .containsExactly("main", "a", "b")
        }
    }
}
```

Having this in place we can just add the following to line 104 to have `branchesToGenerate` already sorted on initialization:


```kotlin
}.sortedWith(branchComparator(defaultBranch))
```

2023-10-16 13:15 UTC, qtzar commented
@jp7677 It feels weird having the branch comparator function sitting outside the class. Probably because I'm just not that used to Kotlin :)

2023-10-16 14:01 UTC, jp7677 approved these changes

2023-10-16 14:01 UTC, merged

2023-10-16 14:05 UTC, jp7677 commented
> @jp7677 It feels weird having the branch comparator function sitting outside the class. Probably because I'm just not that used to Kotlin :)

I guess both, outside the class or as companion object within the class,  would be fine as long as writing tests is still easy. I opted for outside since you could say that sorting with that order is a kind-of general thing. I guess linters would suggest to put it into a separate file with the name `BranchComparator.kt`.