Added support for Dynamic Diagrams
avisi-cloud/structurizr-site-generatr pull request #333
Opened 2023-10-20 19:13 UTC by qtzar

Dynamic Diagrams are now exposed as a tab on the software system.

2023-10-20 19:23 UTC, qtzar commented on src/test/kotlin/nl/avisi/structurizr/site/generatr/site/model/SoftwareSystemPageViewModelTest.kt
> +    fun `dynamic views tab only visible when component diagrams available`() {
```suggestion
    fun `dynamic views tab only visible when dynamic diagrams available`() {
```

2023-10-22 06:09 UTC, jp7677 requested changes
Just one nit, otherwise LGTM!

2023-10-22 06:09 UTC, jp7677 commented on src/main/kotlin/nl/avisi/structurizr/site/generatr/site/model/SoftwareSystemDynamicPageViewModel.kt
> +import nl.avisi.structurizr.site.generatr.hasComponentViews
This import is not needed.

2023-10-22 13:45 UTC, jp7677 approved these changes

2023-10-22 13:46 UTC, merged

2023-10-25 10:36 UTC, mwz commented
Hi, any chance for this to be released anytime soon?