Render PlantUML diagrams in Markdown documents
avisi-cloud/structurizr-site-generatr pull request #411
Opened 2024-01-17 11:02 UTC by dirkgroot

This PR adds support for rendering PlantUML diagrams embedded in Markdown files.

Screenshot:

![image](https://github.com/avisi-cloud/structurizr-site-generatr/assets/3872163/2729a37b-1fbf-4184-ad80-891a5560b8c9)

2024-01-17 15:58 UTC, jp7677 requested changes
Code looks good, very cool! Any chance to add a (very) simple test to https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/src/test/kotlin/nl/avisi/structurizr/site/generatr/site/model/MarkdownToHtmlTest.kt and https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/src/test/kotlin/nl/avisi/structurizr/site/generatr/site/model/AsciidocToHtmlTest.kt ?

2024-01-17 16:10 UTC, dirkgroot commented
> Code looks good, very cool! Any chance to add a (very) simple test to https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/src/test/kotlin/nl/avisi/structurizr/site/generatr/site/model/MarkdownToHtmlTest.kt and https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/src/test/kotlin/nl/avisi/structurizr/site/generatr/site/model/AsciidocToHtmlTest.kt ?

Thanks! Yes, I was planning on doing so. Didn't expect such a fast review 😄.

2024-01-18 09:13 UTC, dirkgroot commented
@jp7677 I've added the tests.

2024-01-19 09:24 UTC, jp7677 requested changes
Just a small suggestion  (and no strong objections if you want to keep it), otherwise LGTM!

2024-01-22 22:19 UTC, jp7677 approved these changes

2024-01-22 22:19 UTC, merged