Add container and component tabs on code view
avisi-cloud/structurizr-site-generatr pull request #507
Opened 2024-05-13 08:06 UTC by LunarN0va

This PR will give the user the option to cycle through all the containers and components that have code views. This will decrease clutter on the code page when too many images get added.

2024-05-13 12:22 UTC, jp7677 requested changes

2024-05-13 12:22 UTC, jp7677 commented on src/main/kotlin/nl/avisi/structurizr/site/generatr/site/SiteGenerator.kt
> +                    ( context.workspace.hasComponentDiagrams(container) or
Let's use the `has...` helper functions also in the block above.

2024-05-14 06:39 UTC, LunarN0va commented on src/main/resources/assets/css/style.css
> +    font-size: 0.75rem;
I'll have a look at it. Thanks! :)

2024-05-14 06:40 UTC, jp7677 commented on src/test/kotlin/nl/avisi/structurizr/site/generatr/site/model/SoftwareSystemPageViewModelTest.kt
> +        .filter { it != Tab.COMPONENT && it != Tab.CODE } // Component & code links are dynamic
Looks like we are also missing a `code views tab only visible when code image views available` test. Would you mind adding that?

2024-05-16 11:24 UTC, jp7677 approved these changes

2024-05-16 14:15 UTC, merged